name: VI Systems
favicon: null
layout_spectrum: 0.8714815557468683
typography_spectrum: 0.7048185726162046
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.846261888043955
  lightness: 0.12542535248212516
  saturation: 0.41095743188634515
  rhythmicContrast: 0.45772210671566427
purpose: []
